name: First task

on:
  push:
    branches:
      - main

jobs:
  say_hello: 
    runs-on: ubuntu-latest
    steps:
        - name: Echo something
          run: echo "something for you!"
          
        - run: echo "another message for you"
