name: CI/CD pipeline

on:
    push:
        branches:
            - main
    
jobs:
    ci-cd:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                node-version: 15
            - run: npm -v
            - run: ls -l




                


