name: CI/CD pipeline

on:
    push:
        branches:
            - main
    
jobs:
    ci-cd:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                node-version: 15
            - run: npm -v
            - run: npm -i npm@7

            - run: cd codebase/rdicidr-0.1.0

            - name: install dependencies
              run: npm install

            - name: lint and run tests
              run: CI=true npm run test

            - name: build
              run: npm run build





                


