name: CI/CD pipeline

on:
    push:
        branches:
            - main
    
jobs:
    ci-cd:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - run: nvm install 15
            - run: nvm use 15



                


