name: terraform apply main

on: 
    push:
        branches:
            - 'main'
        
        paths:
            - 'terraform/environment/main'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  Terraform-validate:
    runs-on: ubuntu-latest

    steps:

        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        
        - name: validate aws credentials
          run: aws sts get-caller-identity

        - uses: hashicorp/setup-terraform@v3

        - run: terraform init
          working-directory: 'terraform/environment/main'

        - run: terraform apply
          working-directory: 'terraform/environment/main'
       
        - run: terraform output -raw bucket_name > bucket.txt
          working-directory: 'terraform/environment/main'

        - name: Upload bucket name as artifact
          uses: actions/upload-artifact@v4
          with:
            name: main-bucket
            path: terraform/environment/main/bucket.txt