name: terraform static app

on: 
    pull_request:
        branches:
            - 'stage'
            - 'dev'
            - 'main'

jobs:
  Terraform-validate:
    runs-on: ubuntu-latest

    steps:

        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - uses: hashicorp/setup-terraform@v3

        - run: terraform init
          working-directory: 'terraform/environment/stage'

        - run: terraform validate
          continue-on-error: true
          working-directory: 'terraform/environment/stage'
      
        - run: terraform plan
          working-directory: 'terraform/environment/stage'

        